/*
 * MQTT.c
 *
 *  Created on: Apr 17, 2019
 *      Author: messi
 */
#include "MQTT.h"

void Encode_MQTT(DataStruct_t *pStructData,char *str){

	/*
	 * Description:
	 * 		encodes the data to a full URL to be puplished
	 * Return:
	 * 		it return void
	 * 		but a passed pointer (*str) will be used to hold the string
	 * 		generated by the Encode function
	 */

	return;
}

DataStruct_t Decode_MQTT(char *str){
	/*
	 * Description:
	 * 		decodes the data into a useful meaning
	 * Return:
	 * 		it return DataStruct type holding the values
	 * 		after decoding the string given to it.
	 */
	DataStruct_t data;

	//implement function body

	return data;

}
